### ISSUE TITLE
Documentation links broken on main site's version page

### ISSUE THREAD

**Issue by JustCodin** [reactjs/reactjs.org#3357] opened 2020-10-30 01:26 UTC
All of the documentation links on 'https://reactjs.org/versions/' are not working.

**Comment by foreverabhi2002** [comment] 2020-12-14 13:01
@JustCodin links are all working fine.
If you are facing any issue on any of the links then please specify or mention here.

**Comment by sijusamson** [comment] 2020-12-14 13:35
@foreverabhi2002 go to version 16.8, and click on "Documentation".

**Comment by foreverabhi2002** [comment] 2020-12-14 14:37
@sijusamson and @JustCodin, Yeah I've got the issue. Thanks for letting me know.

**Comment by foreverabhi2002** [comment] 2020-12-14 14:53
![Screenshot (11)](https://user-images.githubusercontent.com/57245064/102095407-80d66100-3e49-11eb-86ef-1a7480e8e0db.png)

Got this!! the link is not broken the path has been removed and it leads to nowhere check this attachment.
I think it has been removed for purpose.

**Comment by rickhanlonii** [comment] 2021-02-10 03:08
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Closed by rickhanlonii** 2021-02-10 03:08 UTC

**Comment by gaearon** [comment] 2021-02-10 03:46
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
