### ISSUE TITLE
Code sandboxes are broken in concurrent-mode-patterns documentation

### ISSUE THREAD

**Issue by chetangawai** [reactjs/reactjs.org#4216] opened 2022-01-11 16:33 UTC
Code sandboxes mentioned in the 'Concurrent mode patterns' documentation are broken with the below error - 

<img width="653" alt="Screenshot 2022-01-11 at 22 05 42" src="https://user-images.githubusercontent.com/2047393/148983553-6bca79e6-88fc-4b12-a807-63e116e132e7.png">

1. [Wrapping-setstate-in-a-transition](https://codesandbox.io/s/musing-driscoll-6nkie)
2. [Adding a Pending Indicator ](https://codesandbox.io/s/jovial-lalande-26yep)
3. [Transitions Are Everywhere](https://codesandbox.io/s/boring-shadow-100tf)
4. [Baking Transitions Into the Design System](https://codesandbox.io/s/modest-ritchie-iufrh)
and many more

**Comment by harish-sethuraman** [comment] 2022-01-12 06:53
Closing this issue since it is the duplicate of 
- https://github.com/reactjs/reactjs.org/issues/4216

Thanks

**Closed by harish-sethuraman** 2022-01-12 06:53 UTC
