### ISSUE TITLE
Change tutorial codes to hooks

### ISSUE THREAD

**Issue by xiaoxiangmoe** [reactjs/reactjs.org#3255] opened 2020-09-12 07:49 UTC
https://reactjs.org/tutorial/tutorial.html

Codes here using class components. We can change it into hooks.

**Comment by eps1lon** [comment] 2020-09-12 09:39
Duplicate of https://github.com/reactjs/reactjs.org/issues/1782

**Closed by eps1lon** 2020-09-12 09:39 UTC
