### ISSUE TITLE
older versions of the documentation

### ISSUE THREAD

**Issue by pipimiao** [reactjs/reactjs.org#3383] opened 2020-11-11 10:15 UTC
the link of the older versions docoment is l invalid

**Comment by fkhan698** [comment] 2020-11-14 01:45
Could you post the invalid link?

**Comment by rickhanlonii** [comment] 2021-02-10 03:12
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3138

**Closed by rickhanlonii** 2021-02-10 03:12 UTC

**Comment by gaearon** [comment] 2021-02-10 03:47
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
