### ISSUE TITLE
redirect-to-codepen Redirects to Empty Codepen

### ISSUE THREAD

**Issue by Labnann** [reactjs/reactjs.org#4243] opened 2022-01-27 01:40 UTC
Codepen gives an empty pen instead of one with codes when getting redirected from  /redirect-to-codepen

Tested links are found in these pages: 
[Rendering Elements](https://reactjs.org/docs/rendering-elements.html)
[Introducing JSX](https://reactjs.org/docs/introducing-jsx.html)
[Hello World](https://reactjs.org/docs/hello-world.html)

Examples of some not working links:

https://reactjs.org/redirect-to-codepen/rendering-elements/update-rendered-element
https://reactjs.org/redirect-to-codepen/introducing-jsx
https://reactjs.org/redirect-to-codepen/hello-world

**Comment by harish-sethuraman** [comment] 2022-01-27 04:36
This issue seems like a duplicate of 
- https://github.com/reactjs/reactjs.org/issues/4227
Closing this duplicate issue to track there

**Closed by harish-sethuraman** 2022-01-27 04:36 UTC

**Comment by harish-sethuraman** [comment] 2022-01-27 11:39
The links are fixed now. 😄
