### ISSUE TITLE
Sidebar does not collapse when clicked on Nav title.

### ISSUE THREAD

**Issue by fumblehool** [reactjs/reactjs.org#113] opened 2017-10-10 11:39 UTC
* The sidebar navigation links in `Tutorial`, `Community` and `Blog`  does not collapse when clicked.
* The active Title for `Tutorial` and `Blog` is undefined. Turns out `findSectionForPath` is sending `undefined` for them.

**Comment by bvaughn** [comment] 2017-10-10 15:27
> The sidebar navigation links in Tutorial, Community and Blog does not collapse when clicked.

This is intentional 😄  These pages have only 1 section.

> The active Title for Tutorial and Blog is undefined. Turns out findSectionForPath is sending undefined for them.

Works fine (for me) in Blog. It doesn't initially show a highlight in Tutorial because the sidebar highlights which section you've scrolled to- and the page isn't initially scrolled to the first sub-section. (I'd be happy to improve the detection on the Tutorial section to show the first one by default if we haven't scrolled quite that far down, but it seems like a nice to have more than a bug.)

**Comment by bvaughn** [comment] 2017-10-10 15:28
Let's keep chatting if I misunderstood either of the issues you've reported above. I'd also be happy to review a PR to improve the initial offset calculation for the Tutorial page. 😄 

For now I'm going to close this issue though since I think it's working as intended.

**Closed by bvaughn** 2017-10-10 15:28 UTC
