### ISSUE TITLE
Right side navigation shows users the wrong page

### ISSUE THREAD

**Issue by NoahCarnahan** [reactjs/reactjs.org#247] opened 2017-11-06 16:04 UTC
- Navigate to https://reactjs.org/docs/hello-world.html 
- Click "Handling Events" in the right side navigation
- Observer that the user is shown the "Portals" page, not the handling events page

**Comment by bvaughn** [comment] 2017-11-06 16:06
Can't reproduce this behavior. Are you sure you clicked the correct nav entry?

**Comment by NoahCarnahan** [comment] 2017-11-06 16:12
Just double checked and I am indeed clicking on the "Handling Events" nav item. For reference, this is with Firefox 56.0 (64-bit) and Chrome version 61.0.3163.100 (Official Build) (64-bit).

**Comment by bvaughn** [comment] 2017-11-06 16:19
Hm. I'm not able to reproduce this on any browser (or operating systems) I have to test on. I think we would probably have heard of this before if it was a widespread problem. I suspect there's something unique about your system, given the fact that you've also reported another issue (#248) that I've never seen before.

**Comment by bvaughn** [comment] 2017-11-07 10:49
I'm going to close this issue for now because I suspect it's something specific to your setup and I'm not sure what action I can take given that I'm unable to reproduce it. If someone else reports this issue, or if you're able to provide additional info to help track it down, we'll re-open!

**Closed by bvaughn** 2017-11-07 10:49 UTC
Labels: bug: unconfirmed, type: website

**Comment by NoahCarnahan** [comment] 2017-11-07 11:53
Sounds good, thanks for looking into it.
