### ISSUE TITLE
[RFC]: documents should supplement this usage of useState

### ISSUE THREAD

**Issue by yklydxtt** [reactjs/reactjs.org#3640] opened 2021-04-19 04:17 UTC
Put a function in setState,the function will be called,but the official document has't recored this usage
Wxample like this:
```js
const [state,setState]=useState(0);
setState(prevValue => prevValue + 1);
```
I hope add this usage  in official document

**Comment by eps1lon** [comment] 2021-04-19 07:47
Duplicate of https://github.com/reactjs/reactjs.org/issues/3585

**Closed by eps1lon** 2021-04-19 07:47 UTC

**Comment by reza-boroushaki** [comment] 2021-05-07 10:13
Agree

**Comment by reza-boroushaki** [comment] 2021-05-07 10:17
Why Closed!

**Comment by reza-boroushaki** [comment] 2021-05-07 10:17
hey
