### ISSUE TITLE
Docs for older versions of React are unavailable

### ISSUE THREAD

**Issue by jaredp** [reactjs/reactjs.org#142] opened 2017-10-11 23:37 UTC
All documentation for older versions of React has been deleted. The React documentation website only shows documentation for the current version of React.

Documentation for previous versions of React should be available somewhere. Ideally, there's a version picker at the top of the page to select which version of React you're working with, like python.org (for example).

I am on React@15.4.2.  Although we're planning to upgrade to 16, for now we still need to reference the 15.4 docs, especially where 16 introduced breaking changes.

**Comment by clemmy** [comment] 2017-10-11 23:50
Duplicate of https://github.com/reactjs/reactjs.org/issues/85

**Closed** 2017-10-11 23:51 UTC

**Comment by mknmohit** [comment] 2020-10-12 05:37
For react `v15.6.2` https://github.com/reactjs/reactjs.org/issues/85#issuecomment-706874947

**Comment by phamvanlinh20111993** [comment] 2022-10-09 06:18
hi, Mr.mknmohit @mknmohit , how about docs for version < 15, for ex: 14.06, Could you give me the details? thank so much

**Comment by mknmohit** [comment] 2022-10-13 14:02
@phamvanlinh20111993 In the history of react, `v15` was the major release, before that react was releasing minor versions. For example: `0.14.7`. So for these versions, I don't have any docs clones.
