### ISSUE TITLE
Rewrite documentation after Hooks are stable

### ISSUE THREAD

**Issue by ivan-kleshnin** [reactjs/reactjs.org#2034] opened 2019-05-24 16:09 UTC
Hi guys. **Are there any plans to rewrite React docs with Hooks as first-class citizens?**

Hooks take codebases (at least open-source) by storm. 
And now React newbies, like my students, face a dilemma:

* Should they start with older APIs only to find they have to learn and use something else later on?
* Or should they start with Hooks and deal with the unusable official docs which are written in terms of lifecycle events?

I competely realize that it's a huge chunk of work. But I would like to know, at least, if something like that is planned. I'll be fine with whatever decision, but it will affect my tutoring strategy. For example, if Hooks become really ubiquotous next year and React docs become stale I may want to recommend 3rd party resources instead of the official docs.

*The answer to this question may be interesting to many people so I decided to ask it here, on GitHub.*

**Comment by alexkrolick** [comment] 2019-05-24 17:20
See https://github.com/reactjs/reactjs.org/issues/2031

**Comment by nickmccurdy** [comment] 2019-09-26 05:15
Isn't this a duplicate? I totally agree with this issue though, and I'd be happy to discuss in #2031.

**Comment by nickmccurdy** [comment] 2019-09-26 06:00
Duplicate of #1788

**Closed** 2019-09-26 12:03 UTC
