### ISSUE TITLE
Older version documentation missing

### ISSUE THREAD

**Issue by cquick** [reactjs/reactjs.org#3498] opened 2021-01-25 19:44 UTC
I have a project that uses version 16.2 of react, but when I click on the link on the document version history I get an error that the documentation is not found. We are not at a point to be able to upgrade since there are several dependencies that will need to be updated along with the latest version -- so having access to the documentation is very helpful.

**Comment by rickhanlonii** [comment] 2021-01-25 20:38
Hey @cquick, thanks for filing an issue. This is a dupe of https://github.com/reactjs/reactjs.org/issues/3401 so I'm going to close this in lieu of that issue.

**Closed by rickhanlonii** 2021-01-25 20:38 UTC
