### ISSUE TITLE
Improve focus style for search input and nav sidebar headers

### ISSUE THREAD

**Issue by damaera** [reactjs/reactjs.org#164] opened 2017-10-16 07:38 UTC
this look not good for me,
![image](https://user-images.githubusercontent.com/5365957/31600067-3d46a84a-b27f-11e7-9a34-4807c689d0c2.png)

IMO, it need more padding, or maybe when focus, no need to show the outline

**Comment by damaera** [comment] 2017-10-16 07:48
in tree menu, this happens too.
![image](https://user-images.githubusercontent.com/5365957/31600503-f13dd96c-b280-11e7-814c-b0de8909c914.png)

**Comment by bvaughn** [comment] 2017-10-16 16:02
The focus outline is important for usability. We can't remove it unless we provide some other, equally noticeable focus style (which we just haven't designed yet).

I agree that the outline is a bit snug for the search input, but I don't think it's all that bad.

The awkward nav sidebar focus sizing is worse though. It's caused by the recent change to wrap the styled header `<div>` in a clickable `<button>`. The div wasn't written with the assumption that it would be wrapped, and the button includes the vertical padding + margin of the div.

I've fixed this (in commit 71bc3d9) to move the margin to the button itself so the alignment is centered.

**Comment by bvaughn** [comment] 2017-10-16 16:03
I'm going to repurpose this issue to be about creating an alternate focus style that can replace the focus outline.

**Comment by bvaughn** [comment] 2017-10-16 20:07
Check out PR #167 for a potential improvement.

**Comment by bvaughn** [comment] 2017-10-17 16:38
Closed via #167 and commit 71bc3d9.

**Closed by bvaughn** 2017-10-17 16:38 UTC
Labels: difficulty: advanced, good first issue, type: website

**Comment by el1f** [comment] 2017-10-27 14:48
Honestly I think that the sidenav would use the same love that the topnav received, with something like a dedicated focus style. Can I work on that?

**Comment by bvaughn** [comment] 2017-10-31 18:08
Please feel free to submit a PR, @el1f
