### ISSUE TITLE
Links not working properly for Hooks API Reference

### ISSUE THREAD

**Issue by DoviMaj** [reactjs/reactjs.org#3564] opened 2021-03-04 22:21 UTC
How to reproduce: Go to this page https://reactjs.org/docs/hooks-reference.html on Chrome and try clicking on those links: 
![Peek 2021-03-05 00-20](https://user-images.githubusercontent.com/36450233/110038622-a6884d80-7d48-11eb-9e9a-9976357f2bb7.gif)

The URL changes correctly but you aren't taken to the reference. 
Sometimes they do work for me, sometimes not. If they work for your try refreshing the page and clicking again.

**Comment by rickhanlonii** [comment] 2021-03-10 06:52
Thanks for reporting! This is a dupe of https://github.com/reactjs/reactjs.org/issues/3261

**Closed by rickhanlonii** 2021-03-10 06:52 UTC
