### ISSUE TITLE
Older React version documentation links are broken.

### ISSUE THREAD

**Issue by kartiksharma1607** [reactjs/reactjs.org#2976] opened 2020-05-18 10:06 UTC
Try going to React 15 documentation [https://react-legacy.netlify.app/docs/hello-world.html](https://react-legacy.netlify.app/docs/hello-world.html)

Go to search, search for `Refs`.

Page takes you to React 16 documentation instead.

**Comment by gaearon** [comment] 2020-05-18 13:04
Yeah I think it's likely the search only works on the new website.

**Comment by alexkrolick** [comment] 2020-05-18 19:08
It only works on the current version, I believe, even for old react 16 versions.

**Comment by rickhanlonii** [comment] 2021-02-10 03:08
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Closed by rickhanlonii** 2021-02-10 03:08 UTC

**Comment by gaearon** [comment] 2021-02-10 03:46
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
