### ISSUE TITLE
Documentation links missing on versions >=16.9

### ISSUE THREAD

**Issue by a2intl** [reactjs/reactjs.org#3138] opened 2020-07-26 05:14 UTC
On the page https://reactjs.org/versions/ , all of the versions from 16.9 and above (newer) are missing the "Documentation" link.

![image](https://user-images.githubusercontent.com/4722761/88472019-f73aec80-cec3-11ea-9ea4-2670e32cc314.png)

**Comment by kwaimind** [comment] 2020-07-27 08:51
@a2intl are you sure? I'm seeing all the way up to 16.13.1

![image](https://user-images.githubusercontent.com/4730761/88522721-12f2df80-cff7-11ea-9ca1-a1c5154cffb3.png)

**Comment by belovweb** [comment] 2020-08-01 07:12
@kwaimind what @a2intl is trying to say is that versions 15.6-16.8 have both changelog and documentation links, but versions 16.9-16.13.1 have only changelog link (as seen in both your screenshots)

**Comment by kwaimind** [comment] 2020-08-01 10:48
Yeah that's my bad 🙋‍♂️ I totally misread the message.

**Comment by saswatamcode** [comment] 2020-08-09 13:11
Also all the documentation links seem to result in Page Not Found errors. Maybe removing them and just keeping the changelogs would be a good idea @rickhanlonii ?

**Comment by gaearon** [comment] 2020-08-09 13:26
Something broke with the redirects. :-(

**Comment by gaearon** [comment] 2020-08-09 13:26
(But that's a separate problem from us forgetting to update the page.)

**Comment by saswatamcode** [comment] 2020-08-09 13:58
Oh. That's why I couldn't find the `/version/versionNumber` page anywhere.

**Comment by jo-flynn** [comment] 2020-11-25 00:02
How can this be open for months with multiple issues and no action? Not everyone is using the latest and greatest and people often need to reference old docs.

**Comment by gaearon** [comment] 2021-02-10 03:17
Redirects were originally added in https://github.com/reactjs/reactjs.org/pull/801.

You can see there's a script that appends stuff to `_redirects`. My guess is that somehow this script either doesn't run anymore since some Gatsby update, or it doesn't write things in the correct format, or it isn't written at the right time.

If someone wants to look into the cause, it would be highly appreciated.

>How can this be open for months with multiple issues and no action? Not everyone is using the latest and greatest and people often need to reference old docs.

I totally understand your frustration! It slipped through the cracks. We're a small team and there are hundreds of issues across many repos. This one kept coming up so I expected that somebody motivated would send a PR with a fix, but maybe there weren't enough details. I hope there's enough now.

**Comment by gaearon** [comment] 2021-02-10 03:33
Here's my guess https://github.com/reactjs/reactjs.org/pull/3516

**Comment by gaearon** [comment] 2021-02-10 03:40
And here's my workflow for finding the issue, in case someone wants to contribute to similar issues but doesn't know how:

- I looked for where the versions are pulled from. That's `versions.yml`.
- I searched PRs for "versions" and found the PR that introduced this functionality. (Another way to do this would be to look at Git history for `versions.yml` and find when it was checked in.)
- I read the PR (https://github.com/reactjs/reactjs.org/pull/801). It appends some generated stuff to `public/_redirects` on Gatsby build.
- I put a log in that function and did `yarn build` locally. The function ran, but the file was not modified.
- I verified that we do get to the end of the script, so it's something with `appendFile` not working. But I also noticed that there is some _other_ script appending to the same file. That gave me the idea about the race condition.
- I looked at the call to the script and noticed a missing `await`.

The fix ended up being one line.

We totally dropped the ball here and I agree we should have looked much earlier. At some point I assumed the problem was with the hosting, and I even remember bringing this up with Netlify support, but I think I forgot to follow up about this.

_Still_, this is an open source project, and I hope that the above writeup can show how someone motivated to fix this could do it. I didn't have any knowledge about how this version integration was set up, and it didn't take that long to fix. Nice contribution opportunity. :-)

**Closed** 2021-02-10 03:40 UTC
