### ISSUE TITLE
Tutorial side bar links highlighting incorrectly

### ISSUE THREAD

**Issue by goleary** [reactjs/reactjs.org#242] opened 2017-11-05 23:39 UTC
1. goto https://reactjs.org/tutorial/tutorial.html
2. click a scetion on the right hand nav
3. the clicked section highlights, you get taken to it and then the section before the clicked one become highlighted.

looks like this is happening for all section links 

Env: windows 10, Chrome Version 61.0.3163.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/16123225/32420439-257d9596-c23f-11e7-8ede-802a45fc807e.png)

**Comment by bvaughn** [comment] 2017-11-06 13:18
Hm. Interesting.

I am unable to reproduce the behavior you're describing using any of the following OS+browser combinations:
* OS X using Chrome 62, Firefox 56, or Safari 11
* Windows 8 using IE 11 or Chrome 62
* Windows 10 using Edge or Chrome 62

I'll leave this issue open for a bit to see if others are also seeing it.

Are you doing anything other than what you've described, like scrolling a little before/after the click? [This is the code](https://github.com/reactjs/reactjs.org/blob/master/src/templates/components/Sidebar/ScrollSyncSection.js) that determines the active section based on the current scroll position. It's possible the vertical offset is slightly incorrect for your browser but I'm not sure why I can't repro it.

**Comment by bvaughn** [comment] 2017-11-09 14:41
Can't repro this and without further information it's hard to look into, so I'm going to close it for now. If new info is provided that enables us to make further progress on it, I'll re-open! 😄

**Closed by bvaughn** 2017-11-09 14:41 UTC
Labels: bug: unconfirmed, type: website

**Comment by goleary** [comment] 2017-11-30 18:27
Sorry for the late reply.  I am no longer able to repro the issue myself so perhaps it has been fixed.  Thanks for looking in to it @bvaughn
