### ISSUE TITLE
Javascript errors on initial page load of https://reactjs.org/docs/installation.html

### ISSUE THREAD

**Issue by NoahCarnahan** [reactjs/reactjs.org#248] opened 2017-11-06 16:08 UTC
- Navigate to https://reactjs.org/docs/installation.html in a web browser
- A javascript error is shown in the developer console (happening with both chrome version 61.0.3163.100 and firefox 56.0)

I've noticed other js errors throughout the docs that seem to break the right side page navigation.

**Comment by bvaughn** [comment] 2017-11-06 16:11
Like #247, I am also unable to reproduce this.

Could you provide additional information about your OS + browser + plugins you have installed to help identify why you are experiencing these unique issues?

**Comment by NoahCarnahan** [comment] 2017-11-06 16:17
Sure. OS is MacOS 10.12.3. I'm also experiencing this bug with Chrome in incognito mode with no extensions enabled.

**Comment by bvaughn** [comment] 2017-11-06 16:23
OS X 10.12.6 here. Can't reproduce with Chrome 62.0.3202.62.

I did actually see the behavior you described initially when testing with Firefox 56.0 and Safari 11.0, but after refreshing the pages (as well as in incognito mode) I was not able to reproduce.

This makes me suspect a problem in a version of the docs that you may have cached on your computer.

**Comment by bvaughn** [comment] 2017-11-07 10:49
I'm going to close this issue for now because I suspect it's something specific to your setup and I'm not sure what action I can take given that I'm unable to reproduce it. If someone else reports this issue, or if you're able to provide additional info to help track it down, we'll re-open!

**Closed by bvaughn** 2017-11-07 10:49 UTC
Labels: bug: unconfirmed, type: website

**Comment by NoahCarnahan** [comment] 2017-11-07 11:53
Sounds good, thanks for looking into it.
