### ISSUE TITLE
Horizontal scrolling can break on mobile 

### ISSUE THREAD

**Issue by sophiebits** [reactjs/reactjs.org#1404] opened 2018-11-17 11:39 UTC
Spotted this on Twitter: https://twitter.com/wojtekmaj91/status/1063708337177534465

Didn’t verify myself.

**Comment by gaearon** [comment] 2018-11-20 10:29
Also https://twitter.com/fabian_krutsch/status/1064762103553294336

**Comment by omasback** [comment] 2018-11-20 10:38
which browser?

**Comment by jesseyuen** [comment] 2018-11-20 10:39
Hello! Adding a width or max-width of 100% to `<article class="css-174qq1k">` seems to fix the issue for Firefox (63.0.1 ) on desktop. I've not confirmed the issue is fixed on a device yet :)

**Comment by morajabi** [comment] 2018-11-20 10:40
Do you use a JavaScript media query condition for some mobile UI? It might be Gatsby's initial render which uses the prerendered UI, and those JavaScript media's don't get re-evaluated on initial render on mobile.

**Comment by omasback** [comment] 2018-11-20 10:46
the main column div is `display: flex` but it's not `flex-direction: column` even though it shoudl be a column layout

**Comment by manuelitox** [comment] 2018-11-20 10:48
The faster fix is to add `word-break: break-all;` to the wrapper `div.css-j4q8zh`

**Comment by solarsoft0** [comment] 2018-11-20 10:57
got your tweet dan, i just checked, it fine on my android, also tried recreating the url as an intent from twitter it was fine too, i think @wojtekkmaj91 should give us more info, like the device and browser details

**Comment by gaearon** [comment] 2018-11-20 11:07
Thanks everyone!

**Comment by gaearon** [comment] 2018-11-20 11:40
I initially merged https://github.com/reactjs/reactjs.org/pull/1414 but it broke sidebar on desktop. We need a fix that works both on desktop and mobile.

**Closed** 2018-11-20 12:56 UTC
