### ISSUE TITLE
Old Documentation page not found error

### ISSUE THREAD

**Issue by Eshan-Agarwal** [reactjs/reactjs.org#3401] opened 2020-11-23 05:26 UTC
All `React` versions from `16.8`  to `15.6` have `Page Not Found Error` on accessing  `documentation`

To reproduce go here in [version](https://reactjs.org/versions/) list and try to see the [documentation](https://reactjs.org/version/16.0) of any version

**Comment by lipigirl** [comment] 2020-11-25 07:06
So did I

**Comment by swapnalshahil** [comment] 2020-12-24 15:32
I guess their documentation doesn't exist. So it's better to remove the path from there. @eps1lon what's your thought??

**Comment by alexkrolick** [comment] 2020-12-24 19:51
Ok, this is not good. The redirects are not pointing anywhere. I think they used to be inlined in the page. The intent might be to map them here: https://github.com/reactjs/reactjs.org/blob/master/vercel.json

**Comment by swapnalshahil** [comment] 2020-12-27 16:20
@alexkrolick will you please explain #3464 ?! And how this can solve the above issue?

**Comment by rickhanlonii** [comment] 2021-02-10 03:12
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3138

**Closed by rickhanlonii** 2021-02-10 03:12 UTC
Labels: type: website

**Comment by gaearon** [comment] 2021-02-10 03:47
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
