### ISSUE TITLE
Old documentation links are broken

### ISSUE THREAD

**Issue by matyasf** [reactjs/reactjs.org#3514] opened 2021-02-09 12:34 UTC
Go to https://reactjs.org/versions/
Click any of the old documentation links, e.g. https://reactjs.org/version/16.8 or https://reactjs.org/version/16.3
You'll get a 'page not found' page.

**Comment by rickhanlonii** [comment] 2021-02-10 03:08
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Closed by rickhanlonii** 2021-02-10 03:08 UTC

**Comment by gaearon** [comment] 2021-02-10 03:46
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
