### ISSUE TITLE
Typo in function name in tutorial.md

### ISSUE THREAD

**Issue by yourule** [reactjs/reactjs.org#3041] opened 2020-06-16 17:40 UTC
In content/tutorial/tutorial.md on line 443 there's a typo which will break the code if you're following the tutorial
`        onClick={() => this.props.onClick()}
`
Should be
`        onClick={() => this.props.onclick()}
`

**Comment by threepointone** [comment] 2020-06-17 12:29
That doesn't seem right, `onclick` isn't anywhere on the page, that I can see. Are you sure you didn't yourself accidentally write `<Square onclick=..` while following the tutorial?

**Comment by yourule** [comment] 2020-06-17 12:42
<img width="1571" alt="Screenshot 2020-06-17 at 14 40 40" src="https://user-images.githubusercontent.com/2239940/84899281-b8d23680-b0a8-11ea-8e79-09c59b54790b.png">

**Comment by threepointone** [comment] 2020-06-17 12:44
I'm aware of that line, but it doesn't cause an issue, because nowhere is the handler passed as `onclick` to `Square`.

**Comment by yourule** [comment] 2020-06-18 07:27
All I can see is this error when onClick is written with a capital C. If I lower the case the errors goes away and the code runs.

<img width="469" alt="Screenshot 2020-06-18 at 09 25 36" src="https://user-images.githubusercontent.com/2239940/84990648-bf62bb80-b145-11ea-8fdf-d54069d50117.png">

**Comment by threepointone** [comment] 2020-06-18 11:12
Please read what I just said. In your code, where you actually use the Square component, (which will look like `<Square...` please see whether you're passing the handler as `onclick={...`, or `onClick={...`. The former is wrong, and isn't what the tutorial does. 

Please share a reproducible version in codesandbox or as a git repo if you'd like further help debugging this.

**Comment by rickhanlonii** [comment] 2020-07-08 02:15
Yeah I agree with @threepointone `onClick={() => this.props.onClick()}` looks correct, looks like you may have had a typo copying it over. Closing for now but can re-open if you provide a repro example.

**Closed by rickhanlonii** 2020-07-08 02:15 UTC
