### ISSUE TITLE
Navigation breaks down on a page without .html extension

### ISSUE THREAD

**Issue by siddharthlatest** [reactjs/reactjs.org#249] opened 2017-11-06 18:11 UTC
Hey, so if you go to a page like https://reactjs.org/docs/handling-events (without the .html suffix) and try navigating to any other page from the sidebar navigation or anchor tags in the page, it just doesn't work. Any ideas?

**Comment by bvaughn** [comment] 2017-11-07 10:46
Duplicate of #241 😄 Let's talk there.

**Closed by bvaughn** 2017-11-07 10:46 UTC
Labels: bug: confirmed, duplicate
