### ISSUE TITLE
"Try it on CodePen" links not working on Docs Main Concepts

### ISSUE THREAD

**Issue by Cwarcup** [reactjs/reactjs.org#4244] opened 2022-01-27 01:53 UTC
Hello, 

all the examples with links to CodePen get redirected to a blank CodePen document.

For example, [https://reactjs.org/redirect-to-codepen/components-and-props/rendering-a-component](url) gets redirect to https://codepen.io/pen?layout=left.

Have reproduced the issue on the Hello World, Introducing JSX, Rendering Elements, and Components and Props page. 
![Screen Shot 2022-01-26 at 5 44 03 PM](https://user-images.githubusercontent.com/88569957/151277005-be16829e-cd74-4961-83d1-4adc52dec1e3.png)
![Screen Shot 2022-01-26 at 5 49 31 PM](https://user-images.githubusercontent.com/88569957/151277170-0e1fbca8-5b0d-4bf4-b2f0-1fc6fc2a64ad.png)

**Comment by harish-sethuraman** [comment] 2022-01-27 04:35
This issue seems like a duplicate of
- https://github.com/reactjs/reactjs.org/issues/4227

**Closed by harish-sethuraman** 2022-01-27 04:35 UTC

**Comment by harish-sethuraman** [comment] 2022-01-27 11:40
The links are fixed now. 😄

**Comment by PhilipSada** [comment] 2022-01-27 12:53
Just testing this again
