### ISSUE TITLE
typing issue in document

### ISSUE THREAD

**Issue by k9982874** [reactjs/reactjs.org#307] opened 2017-11-20 07:42 UTC
![image](https://user-images.githubusercontent.com/3873648/33007347-59af813c-ce09-11e7-97a1-dac60fda4dca.png)

**Comment by clemmy** [comment] 2017-11-20 16:46
What's the problem here?

**Comment by bvaughn** [comment] 2017-11-20 17:11
Hi @k9982874. 😄 

I don't see any problem with the code you've highlighted. Could you clarify?

**Comment by bvaughn** [comment] 2017-11-20 22:50
I'm going to close this for now because I think the docs in question are fine.

I can re-open it later if we get more clarification on what the problem is. ❤️

**Closed by bvaughn** 2017-11-20 22:50 UTC
