### ISSUE TITLE
All Documentation Links are broken on the "versions" route

### ISSUE THREAD

**Issue by michaelagard** [reactjs/reactjs.org#3268] opened 2020-09-16 20:44 UTC
To reproduce, follow this link https://reactjs.org/versions/ and click on any of the links titled "Documentation" under the version numbers. Example broken URL route: https://reactjs.org/version/16.2

**Comment by eps1lon** [comment] 2020-09-21 08:25
[These used to work](http://web.archive.org/web/20200725132751/https://reactjs.org/version/16.2) and the URLs listed in the repo (https://github.com/reactjs/reactjs.org/blob/master/content/versions.yml) are still available. Maybe something broke when updating gatsby?

**Comment by saswatamcode** [comment] 2020-09-26 09:24
This seems to be the same [issue](https://github.com/reactjs/reactjs.org/issues/3138)

**Comment by rickhanlonii** [comment] 2021-02-10 03:07
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268 which has more info.

**Closed by rickhanlonii** 2021-02-10 03:07 UTC

**Comment by gaearon** [comment] 2021-02-10 03:09
Did you mean some other issue number? Self-referential.

**Comment by gaearon** [comment] 2021-02-10 03:09
I assume you mean https://github.com/reactjs/reactjs.org/issues/3138

**Comment by rickhanlonii** [comment] 2021-02-10 03:11
Yeah, thanks.
